# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

DEVISE_SECRET_KEY: '4fc3e8284345e83cb7804a1e8698d5df1d39724a8f04c2ef7f5750b3498691a6c9db5ed0d17bbddd0fdaa59f4c07bb21093ef9bbcd2bfa327e31282861da1a65'
SENDGRID_PASSWORD: '2oz2hwfz'
SENDGRID_USERNAME: 'app32722249@heroku.com'

AWS_ACCESS_KEY_ID: AKIAIP4CRZD7GNGUHVSQ
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: scheduler-development-wilbanks
production:
  AWS_BUCKET: scheduler-production-wilbanks

TWILIO_ACCOUNT_SID: 'ACd7c0591256b00094cf9f60c41b7a5d51'
TWILIO_AUTH_TOKEN: 'edc5cd8e9f6164cf6dbd0fa0735a1014'
TWILIO_PHONE_NUMBER: '14246723527'